---
name: Build and Push API Docker image
on:
  push:
    branches: [ "master" ]
jobs:
  job_id:
    name: Build and push image to docker hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: | 
           docker build --build-arg TOKEN=${{ secrets.TOKEN }} --build-arg GUILD_ID=${{ secrets.GUILD_ID }} --build-arg CLIENT_ID=${{ secrets.CLIENT_ID }} --build-arg CHANNEL_ID=${{ secrets.CHANNEL_ID }} -t carage34/tip4search:latest .
            docker push carage34/tip4search:latest
